### ISSUE TITLE
VROOM category functions - Provide information of unassigned tasks in the result columns

### ISSUE THREAD

**Issue by krashish8** [pgRouting/vrprouting#26]
Currently, the result columns only contain the scheduled tasks (i.e. the tasks assigned to the vehicles). We shall also provide the details of the unassigned tasks in the output.

What would be a good way to do this?
- Raise a NOTICE listing all the unassigned tasks.
- Include the unassigned tasks in the result column itself, keeping the value of other columns as -1: `vehicle_seq = -1`, `vehicle_seq = -1`, `step_type = 7` (meaning unassigned), etc.

I think the second option is preferable, as this would also help in displaying other task parameters in the result columns, without any extra cost. Raising a notice won't be good enough if a lot of tasks are unassigned, and it might also be difficult to parse the data in the notice.

**Comment by dkastl** [comment]
Having a "special" vehicle could be a good idea. @cvvergara , in the on-demand bus VRP you assigned all unassigned orders to a dummy vehicle. Maybe you have some suggestion?

**Comment by krashish8** [comment]
From the code, I guess that Vicky created a phony vehicle (id = -1) with max capacity and max window with the start & end points of the first vehicle, and added that manually to the problem before solving.

I don't think we need to add a phony vehicle manually to the problem (VROOM might be doing something similar internally). We just need to pass the data to VROOM and in the result, we can show all the unallocated tasks in a vehicle with id = -1.
